In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Get strip array from txt file
strips = np.genfromtxt("SBND_ADCCalib-V4.txt", delimiter=None)

In [2]:
print(strips.shape)
print(strips)

# Remove column 3 it's gain and we don't need it
reduced_strips = strips[:,0:3]

print(reduced_strips.shape)
print(reduced_strips)

(768, 4)
[[7.900e+01 0.000e+00 1.640e+02 1.778e+03]
 [7.900e+01 1.000e+00 1.740e+02 1.694e+03]
 [7.900e+01 2.000e+00 1.750e+02 1.582e+03]
 ...
 [1.040e+02 2.900e+01 1.350e+02 1.659e+03]
 [1.040e+02 3.000e+01 1.230e+02 1.967e+03]
 [1.040e+02 3.100e+01 1.280e+02 1.666e+03]]
(768, 3)
[[ 79.   0. 164.]
 [ 79.   1. 174.]
 [ 79.   2. 175.]
 ...
 [104.  29. 135.]
 [104.  30. 123.]
 [104.  31. 128.]]


In [3]:
mac5_mapping = [81, 79, 80, 95, 94, 93, 104, 103, 102, 90, 89, 91, 101, 100, 99, 87, 86, 88, 98, 97, 96, 84, 83, 85]

In [4]:
mac5_mapping.index(79)

1

In [5]:
for x in reduced_strips :
    x[0] = mac5_mapping.index(x[0])
    
print(reduced_strips)

[[  1.   0. 164.]
 [  1.   1. 174.]
 [  1.   2. 175.]
 ...
 [  6.  29. 135.]
 [  6.  30. 123.]
 [  6.  31. 128.]]


In [16]:
for x in reduced_strips :
   print("[", str(x[0] * 32 + x[1]), ", " + str(x[2]) + "],")

[ 32.0 , 164.0],
[ 33.0 , 174.0],
[ 34.0 , 175.0],
[ 35.0 , 174.0],
[ 36.0 , 175.0],
[ 37.0 , 174.0],
[ 38.0 , 174.0],
[ 39.0 , 165.0],
[ 40.0 , 175.0],
[ 41.0 , 188.0],
[ 42.0 , 175.0],
[ 43.0 , 175.0],
[ 44.0 , 174.0],
[ 45.0 , 187.0],
[ 46.0 , 156.0],
[ 47.0 , 183.0],
[ 48.0 , 175.0],
[ 49.0 , 175.0],
[ 50.0 , 188.0],
[ 51.0 , 174.0],
[ 52.0 , 174.0],
[ 53.0 , 168.0],
[ 54.0 , 174.0],
[ 55.0 , 174.0],
[ 56.0 , 174.0],
[ 57.0 , 144.0],
[ 58.0 , 174.0],
[ 59.0 , 187.0],
[ 60.0 , 174.0],
[ 61.0 , 174.0],
[ 62.0 , 173.0],
[ 63.0 , 156.0],
[ 64.0 , 125.0],
[ 65.0 , 159.0],
[ 66.0 , 164.0],
[ 67.0 , 155.0],
[ 68.0 , 143.0],
[ 69.0 , 164.0],
[ 70.0 , 154.0],
[ 71.0 , 140.0],
[ 72.0 , 153.0],
[ 73.0 , 143.0],
[ 74.0 , 152.0],
[ 75.0 , 155.0],
[ 76.0 , 148.0],
[ 77.0 , 163.0],
[ 78.0 , 137.0],
[ 79.0 , 135.0],
[ 80.0 , 155.0],
[ 81.0 , 143.0],
[ 82.0 , 140.0],
[ 83.0 , 152.0],
[ 84.0 , 141.0],
[ 85.0 , 146.0],
[ 86.0 , 140.0],
[ 87.0 , 140.0],
[ 88.0 , 132.0],
[ 89.0 , 132.0],
[ 90.0 , 124.0