In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Get strip array from txt file
strips = np.genfromtxt("SBND_CRTpositionsSiPM-V1.txt", delimiter=None)

In [2]:
# Debug by printing
# Column  0   is strip ID
# Columns 1-3 are [x, y, z] positions in building coordinates
print(strips)

[[9500.        331.       1046.25     ...    0.          0.
     0.      ]
 [9501.        331.       1046.25     ...    0.          0.
     0.      ]
 [9502.        331.       1046.25     ...    0.          0.
     0.      ]
 ...
 [8329.        868.801135  100.       ...    0.          0.
     0.      ]
 [8330.        868.901135  100.       ...    0.          0.
     0.      ]
 [8331.        874.751147  100.       ...    0.          0.
     0.      ]]


In [3]:
# Just learning how to use python
print(type(strips))
print(strips.shape)

<class 'numpy.ndarray'>
(768, 7)


In [4]:
# Remove columns 4 onwards, not needed
reduced_strips = strips[:,0:4]

In [5]:
# Check I did it right
print(reduced_strips.shape)

(768, 4)


In [6]:
# And again...
print(reduced_strips)

[[9.50000000e+03 3.31000000e+02 1.04625000e+03 4.05000000e+00]
 [9.50100000e+03 3.31000000e+02 1.04625000e+03 9.90000000e+00]
 [9.50200000e+03 3.31000000e+02 1.04625000e+03 1.00000000e+01]
 ...
 [8.32900000e+03 8.68801135e+02 1.00000000e+02 2.76000000e+02]
 [8.33000000e+03 8.68901135e+02 1.00000000e+02 2.76000000e+02]
 [8.33100000e+03 8.74751147e+02 1.00000000e+02 2.76000000e+02]]


In [7]:
# The conversion to our usual detector coordinates that I understand
# First swap y & z
def Swap(arr, start_index, last_index):
    arr[:, [start_index, last_index]] = arr[:, [last_index, start_index]]
    
Swap(reduced_strips, 2, 3)

# Invert x-axis
reduced_strips = reduced_strips * [1, -1, 1, 1]

# Transform origin position (and add 300 to mac5 to match those in Igor's slides)
reduced_strips = reduced_strips + [0, 471, -395, -265]

In [8]:
# Check transformation
print(reduced_strips)

[[9500.        140.       -390.95      781.25    ]
 [9501.        140.       -385.1       781.25    ]
 [9502.        140.       -385.        781.25    ]
 ...
 [8329.       -397.801135 -119.       -165.      ]
 [8330.       -397.901135 -119.       -165.      ]
 [8331.       -403.751147 -119.       -165.      ]]


In [9]:
map = [ 81, 79, 80, 95, 94, 93, 104, 103, 102, 90, 89, 91, 101, 100, 99, 87, 86, 88, 98, 97, 96, 84, 83, 85]
map.index(85)

23

In [10]:
for strip in reduced_strips:
    print("SiPM:        ", map.index(strip[0] // 100) * 32 + (strip[0] % 100))
    print("Position:    (", strip[1], ", ", strip[2], ", ", strip[3], ")")
    print()

SiPM:         96.0
Position:    ( 140.0 ,  -390.95 ,  781.25 )

SiPM:         97.0
Position:    ( 140.0 ,  -385.1 ,  781.25 )

SiPM:         98.0
Position:    ( 140.0 ,  -385.0 ,  781.25 )

SiPM:         99.0
Position:    ( 140.0 ,  -379.15 ,  781.25 )

SiPM:         100.0
Position:    ( 140.0 ,  -379.05 ,  781.25 )

SiPM:         101.0
Position:    ( 140.0 ,  -373.2 ,  781.25 )

SiPM:         102.0
Position:    ( 140.0 ,  -373.1 ,  781.25 )

SiPM:         103.0
Position:    ( 140.0 ,  -367.249999 ,  781.25 )

SiPM:         104.0
Position:    ( 140.0 ,  -367.149999 ,  781.25 )

SiPM:         105.0
Position:    ( 140.0 ,  -361.3 ,  781.25 )

SiPM:         106.0
Position:    ( 140.0 ,  -361.2 ,  781.25 )

SiPM:         107.0
Position:    ( 140.0 ,  -355.349999 ,  781.25 )

SiPM:         108.0
Position:    ( 140.0 ,  -355.249999 ,  781.25 )

SiPM:         109.0
Position:    ( 140.0 ,  -349.399998 ,  781.25 )

SiPM:         110.0
Position:    ( 140.0 ,  -349.299998 ,  781.25 )

SiPM:      